use_frameworks!

platform :ios, '8.0'

target 'JenkinsPGYSDK_Example' do
  pod 'JenkinsPGYSDK', :path => '../'

  target 'JenkinsPGYSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
